# Generated by Django 3.0.8 on 2020-08-03 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0002_tutorial_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='description',
            field=models.CharField(default='', max_length=2000),
        ),
    ]
