# Generated by Django 3.0.8 on 2020-08-03 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MapResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zipcode', models.CharField(default='', max_length=200)),
                ('latitude', models.CharField(default='0', max_length=200)),
                ('longitude', models.CharField(default='0', max_length=200)),
                ('city', models.CharField(default='', max_length=200)),
                ('state', models.CharField(default='', max_length=200)),
                ('county', models.CharField(default='', max_length=200)),
                ('description', models.CharField(default='', max_length=2000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
